### ISSUE TITLE
[Enhancement] Star Limit

### ISSUE THREAD

**Issue by bdotsamir** [1Computer1/hoshi#6]
Hello. This is a request for a feature on the bot: a star limit. For those who don't know, a star limit is basically instead of Hoshi posting every message with one star react on it, you could set however many star reactions are needed before it posts said message to the starboard. It's a feature many other bots with starboard capabilities have, and since this is a bot solely dedicated to a starboard system, it should have this feature.

If I can figure out how to code it, I will probably open up a PR if you guys don't get to it first :P 

Thanks :)
Akii#2111

**Comment by 1Computer1** [comment]
This has been implemented, sorry for the wait!
Will be available to all in a bit.
